#!/bin/bash
#
# Install programs required for running timers
# Create aliases for timers and add to ~/.bash_aliases
# Execute . ~/.bashrc file
#
# Copyright (C)   2016    Madhav Datt
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#

sudo modprobe pcspkr
sudo apt-get install beep
cd /etc
mkdir super-focus
mv ~/Downloads/super-focus/* /etc/super-focus
cd super-focus
chmod 755 src/prod_timer
chmod 755 src/timer

. ~/.bashrc

rm -rf ~/Downloads/super-focus
